// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission4.Models;

namespace Mission4.Migrations
{
    [DbContext(typeof(MovieInputContext))]
    [Migration("20220127043025_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission4.Models.MovieInput", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Action/Adventure",
                            Director = "Chris Columbus",
                            Edited = false,
                            Notes = "Awesome movie!",
                            Rating = "PG",
                            Title = "Hary Potter and the Sorcerers Stone",
                            Year = 2001
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Romance/Drama",
                            Director = "Greta Gerwig",
                            Edited = false,
                            LentTo = "Sav",
                            Notes = "Loved watching it! ",
                            Rating = "PG",
                            Title = "Little Women",
                            Year = 2019
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Romance/Comedy",
                            Director = "Andy Fickman",
                            Edited = false,
                            LentTo = "Lexi",
                            Notes = "Love Betty White! ",
                            Rating = "PG",
                            Title = "You Again",
                            Year = 2010
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
